[package]
name = "exchange"
version = "0.1.0"
edition = "2021"


[dependencies]
cosmwasm-std = "2.2.0"
schemars = "0.8.21"
cw-storage-plus = "2.0.0"
serde = { version = "1.0.217", features = ["std"] }
aes-gcm = "0.10.3"
thiserror = "2.0.11"

[dev-dependencies]
